name: CI - Python (face recognition)

on:
  push:
    branches: [ main ]
    paths:
      - 'face-recognition python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    paths:
      - 'face-recognition python/**'
      - '.github/workflows/python-ci.yml'
  workflow_dispatch: {}

permissions:
  contents: read

defaults:
  run:
    working-directory: "face-recognition python"

jobs:
  python_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo files
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'   # <— changed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q
